### ISSUE TITLE
公众号提供的服务出现故障

### ISSUE THREAD

**Issue by Emin-Zhang** [shaonianzhentan/ha_wechat#2]
大佬，按照教程设置后，给公众号发送消息，提示该公众号提供的服务出现故障，请稍后再试。
![1676009536335](https://user-images.githubusercontent.com/61353294/218016419-9e78a38c-6fdd-44d2-b275-f912582d29aa.png)

**Comment by shaonianzhentan** [comment]
你插件没安装成功吗？

**Comment by Emin-Zhang** [comment]
装了插件的，homeassistant家庭助理插件确定用户id和订阅主题正确
![image](https://user-images.githubusercontent.com/61353294/218355696-f4400998-146e-424a-a475-f1d7bfc016db.png)
![image](https://user-images.githubusercontent.com/61353294/218355759-76f65473-3ee8-4a9a-9e59-8561b4f0b228.png)

**Comment by shaonianzhentan** [comment]
在配置用户ID和订阅主题时，一定要确定去掉前后空格

还有就是多试几次，免费的MQTT服务不保证百分百稳定

**Comment by Emin-Zhang** [comment]
好的  我再试试

**Comment by Emin-Zhang** [comment]
> 在配置用户ID和订阅主题时，一定要确定去掉前后空格
> 
> 还有就是多试几次，免费的MQTT服务不保证百分百稳定

大佬，请问mqtt能使用自己本地的服务吗。

**Comment by shaonianzhentan** [comment]
正常来说应该配置好了就直接可以使用的，非常的简单

我觉得应该是哪一步没操作对，这个需要自行排查，一般使用最新版都没啥问题

如果实在想用，又不会搞，可以加Q`635147515`付费帮看

**Comment by Emin-Zhang** [comment]
好的  感谢感谢  我再折腾折腾

**Comment by shaonianzhentan** [comment]
> 好的 感谢感谢 我再折腾折腾

我重新调整了一下，你可以安装配置后调用生成二维码服务试试，
如果无法生成二维码，说明连接MQTT服务有问题

**Comment by Emin-Zhang** [comment]
> 

大佬，调用生成二维码服务在哪里，找半天没找着...

**Comment by Emin-Zhang** [comment]
另外，当我更新最新的conversion集成后，重启报这个错：
![1678678070034](https://user-images.githubusercontent.com/61353294/224602192-903a18fe-8c75-4447-872e-b9cd0a3574a4.jpg)
我的ha版本是：
![1678678440364](https://user-images.githubusercontent.com/61353294/224602261-fac388d8-6a7d-4215-b1e8-86eb2146a410.jpg)，docker运行的。

**Comment by shaonianzhentan** [comment]
> 另外，当我更新最新的conversion集成后，重启报这个错： ![1678678070034](https://user-images.githubusercontent.com/61353294/224602192-903a18fe-8c75-4447-872e-b9cd0a3574a4.jpg) 我的ha版本是： ![1678678440364](https://user-images.githubusercontent.com/61353294/224602261-fac388d8-6a7d-4215-b1e8-86eb2146a410.jpg)，docker运行的。

你的版本太旧了，请将HomeAssistant升级到2023年3月份的版本

**Comment by shaonianzhentan** [comment]
> > 
> 
> 大佬，调用生成二维码服务在哪里，找半天没找着...

![image](https://user-images.githubusercontent.com/5294022/224616711-d45902d3-b5dc-4f82-bae6-9af7efc056cc.png)

**Comment by Emin-Zhang** [comment]
> 

好  我研究下怎么升级docker运行的ha版本。上边提到的生成二维码服务调用成功了，小程序扫码绑定后，发送命令显示：请求异常：request:fail fail:time out

**Comment by shaonianzhentan** [comment]
> > 
> 
> 好 我研究下怎么升级docker运行的ha版本。上边提到的生成二维码服务调用成功了，小程序扫码绑定后，发送命令显示：请求异常：request:fail fail:time out

你之前使用在NodeRED中安装过这个插件吗？

**Comment by Emin-Zhang** [comment]
ha升级到最新版本后，可以微信控制了。感谢大佬。
